- name: file create test playbook
  hosts: all
  tasks:
    - name: "create file '/tmp/{{ file_name }}' if it does not exist"
      command: touch "/tmp/{{ file_name }}"
      args:
        creates: "/tmp/{{ file_name }}"

    - name: "check that the file '/tmp/{{ file_name }}'' was created"
      stat:
        path: "/tmp/{{ file_name }}"
      register: file_stat
      fail:
        msg: "the file '{{ file_name }}' was not created"
      when: file_stat.stat.exists == False