- name: file create test playbook
  hosts: all
  tasks:
    - name: "create file '/tmp/{{ file_name }}' if it does not exist"
      copy:
        src: ""
        dest: "/tmp/{{ file_name }}"
        mode: 0644

    - name: "check that the file '/tmp/{{ file_name }}' was created"
      stat:
        path: "/tmp/{{ file_name }}"
      register: file_stat

    - fail:
        msg: "the file '/tmp/{{ file_name }}' was not created"
      when: file_stat.stat.exists == False