- name: file create test playbook
  hosts: all
  tasks:
    - name: create file "/tmp/{{ file_name }}" if it does not exist
      copy:
        content: ""
        dest: "/tmp/{{ file_name }}"
        force: no
        group: sys
        owner: root
        mode: 0555

    - name: check that the file "/tmp/{{ file_name }}" was created
      stat:
        path: "/tmp/{{ file_name }}"
      register: file_stat
      failed_when: file_stat.stat.exists == False