- name: file delete test playbook
  hosts: all
  tasks:
    - name: delete file if it exists
      file:
        state: absent
        path: "/tmp/{{ file_name }}"
     
    - name: ensure file is deleted
      stat:
        path: "/tmp/{{ file_name }}"
      register: file_stat
      failed_when: file_stat.stat.exists == True